export enum ROUTES {
    engine='Engines',
    fuel= 'Feuls',
    filters= 'Filters',
    vehiclemachine='Vehicle Machine',
    make="Make",
    model="Model",
    vehicle="Vehicle",
    enginedetails="Engine Detail",
    generator="Generator",
    packages="Packages",
    OilDetails = "Oil Detail",
    OilManfacture='Oil Manufacture',
    OilType='Oil Type',
    OilGrade = 'Oil Grade',
    OilEngineType='Oil Engine Type',
    year='Year',
    color='Color',
    business= 'Business Type',
    testLocation = 'Test Location'
}   
